### ISSUE TITLE
Issue with reading ALPHABETA input and other multicolvar module objects

### ISSUE THREAD

**Issue by Tenchberry** [openmm/openmm-plumed#14]
I have successfully installed the plugin, although when running my script for metadynamics using any of the multicolvar to develop a collective variable for biasing, I receive this error on reading atoms:-
The example below is for the ALPHABETA object.

PLUMED: Action ALPHABETA
PLUMED:   with label @1
PLUMED: ERROR in input to action ALPHABETA with label @1 : No atoms have been read in 
PLUMED:  

I do not receive this kind of error when running using with other MD engines/packages patched to PLUMED, and using the same input files. Is there a specific problem with my build for the plugin or OpenMM in this respect? My build was made rather recently, if this provides some insight.

**Comment by peastman** [comment]
I'm not sure what that error means.  It's coming from Plumed, not OpenMM.  I did find a forum thread where someone was getting a similar error message: https://groups.google.com/forum/#!topic/plumed-users/zE2aPPOVkPU.  In that case, the problem was an error in their Plumed script.  Does the explanation there help?

**Comment by raimis** [comment]
I agree with @peastman, this looks like a *PLUMED* issue rather than *OpenMM-PLUMED*.  If it is still problem, it should be reported at https://github.com/plumed/plumed2
